enum events {
    PING= 'PING',
	UPDATE = 'FILE_UPDATE',
	DELETE = 'FILE_DELETE',
	COMMENT = 'FILE_COMMENT',
	VERSION_UPDATE = 'FILE_VERSION_UPDATE',
	LIBRARY_PUBLISHED = 'LIBRARY_PUBLISH',
}

enum blockAction {
    SUBSCRIPTIONS='GET_SUBSCRIPTIONS',
    FILES = 'GET_FILES',
    PROJECTS = 'GET_PROJECTS',
    TEAMS = 'GET_TEAMS',
    REPLY = 'REPLY_TO_COMMENT',
    OPEN_FILE = 'OPEN_FILE',
    REACT = 'REACT_TO_COMMENT',
    POST = 'POST_REPLY',
    FILE_ACTIONS = 'FILES_ACTIONS',
    COMMENT = 'COMMENT_ON_FILE',
}
export {events, blockAction};
